version: "3"
services:
  typo3:
    build: .
    ports:
      - "80:80"
    volumes:
      - fileadmin:/var/www/html/fileadmin
      - typo3conf:/var/www/html/typo3conf
      - uploads:/var/www/html/uploads
    networks:
      - backend

  database:
    image: mysql:5.7
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_USER=${MYSQL_USER:-typo3}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE:-typo3}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    networks:
      - backend

  # For using PostgreSQL instead of MySQL, use the following "database"
  # service instead:
  #
  # database:
  #   image: postgres:12.1
  #   environment:
  #     - "POSTGRES_USER=${POSTGRES_USER:-typo3}"
  #     - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}"
  #     - "POSTGRES_DATABASE=${POSTGRES_DATABASE:-typo3}"
  #   networks:
  #     - backend

volumes:
  database:
  fileadmin:
  typo3conf:
  uploads:

networks:
  backend:
