name: Check for new releases

on:
  schedule:
    - cron: "45 * * * *"

jobs:
  updater:

    runs-on: ubuntu-latest
    container: golang:1.13

    steps:
      - uses: actions/checkout@v2

      - name: Run updater
        run: |
          sh -c "cd ./updater && go build -o ../run-updater"
          ./run-updater \
            --access-token ${{ secrets.ACCESS_TOKEN }}
