name: Build and test TYPO3 10.3 image

on:
  push:
    paths:
      - '10.3/Dockerfile'
      - '10.3/docker-compose.yml'
  pull_request:
    paths:
      - '10.3/Dockerfile'
      - '10.3/docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Build and start image
        run: |
          cd 10.3
          docker-compose build
          docker-compose up -d

          sleep 20

          curl -vLf http://localhost
          docker-compose down -v
